import './game.css';
type Clip={id:string;name:string;views:number};
const rounds:[Clip,Clip][]=[
[{id:'dQw4w9WgXcQ',name:'Never Gonna Give You Up',views:1510000000},{id:'J---aiyznGQ',name:'Keyboard Cat',views:75000000}],
[{id:'9bZkp7q19f0',name:'Gangnam Style',views:5300000000},{id:'OPf0YbXqDm0',name:'Uptown Funk',views:530000000}],
[{id:'kffacxfA7G4',name:'Baby',views:3200000000},{id:'2Vv-BfVoq4c',name:'Perfect',views:3900000000}],
[{id:'XqZsoesa55w',name:'Baby Shark Dance',views:16000000000},{id:'YQHsXMglC9A',name:'Hello',views:3300000000}],
[{id:'fJ9rUzIMcZQ',name:'Bohemian Rhapsody',views:1900000000},{id:'60ItHLz5WEA',name:'Faded',views:3900000000}]
];
type State={round:number;coins:number;stake:number;streak:number;best:number;result:null|{win:boolean}};
const initial:State={round:0,coins:1000,stake:50,streak:0,best:0,result:null};
let state:State={...initial};
try{const saved=JSON.parse(localStorage.getItem('hypecheck-v1')||'null');if(saved)state={...initial,...saved,result:null};}catch{}
state.round=Math.max(0,Math.min(rounds.length-1,state.round));
const save=()=>localStorage.setItem('hypecheck-v1',JSON.stringify(state));
const $=(s:string)=>document.querySelector<HTMLElement>(s)!;
const fmt=(n:number)=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n);
function card(c:Clip,i:number){return `<article class="clip"><div class="clip-head"><b>${i?'B':'A'}</b><span>INTERNET CLASSICS</span><span>${state.result?fmt(c.views)+' VIEWS':'VIEWS HIDDEN'}</span></div><div class="video" id="video${i}" style="background-image:linear-gradient(0deg,#0008,#0002),url(https://i.ytimg.com/vi/${c.id}/hqdefault.jpg)"><button class="play" data-play="${i}"><strong>▶</strong><small>Watch the clip</small></button></div><div class="clip-body"><h3>${c.name}</h3><p>Watch it. Trust your gut. Make your call.</p><button class="pick" data-pick="${i}" ${state.result||state.coins<state.stake?'disabled':''}>Back clip ${i?'B':'A'} &nbsp; ${state.stake} coins ↗</button></div></article>`}
function render(){const pair=rounds[state.round];$('#app').innerHTML=`<header><div class="head-inner"><a class="brand" href="./"><span class="mark">↯</span><span><b>hype<span>check</span></b><small>THE INTERNET GAME</small></span></a><div class="head-actions"><span class="pill lime">◎ &nbsp; YOUR COINS <b>${state.coins.toLocaleString()}</b></span><span class="pill">♨ &nbsp; STREAK <b>${state.streak} in a row</b></span><button class="info" id="info">ⓘ</button></div></div></header><main><section class="hero"><div class="kicker"><i></i> TWO CLIPS. ONE BIG CALL.</div><h1>Which one broke<br>the <em>internet?</em></h1><p>The views are hidden. Your instincts aren’t.<br>Back the bigger hit and prove you know the feed.</p></section><section class="game"><div class="progress"><b>ROUND ${String(state.round+1).padStart(2,'0')} / ${String(rounds.length).padStart(2,'0')}</b><div>${rounds.map((_,i)=>`<i class="${i===state.round?'active':''}"></i>`).join('')}</div><b>♧ &nbsp; PERSONAL BEST ${state.best}</b></div><div class="clips">${card(pair[0],0)}<div class="vs">VS</div>${card(pair[1],1)}</div><div class="stakes"><div><span>◎</span><strong>How sure are you?</strong><small>Choose your stake, then back a clip.</small></div><div class="stake-buttons">${[10,50,100].map(n=>`<button data-stake="${n}" class="${state.stake===n?'selected':''}" ${state.result||state.coins<n?'disabled':''}>${n} coins</button>`).join('')}</div><small>2× return on a correct call</small></div>${state.result?`<div class="result ${state.result.win?'won':'lost'}" role="status"><div><strong>${state.result.win?'You called it.':'The internet disagrees.'}</strong><p>${pair[0].name}: ${fmt(pair[0].views)} · ${pair[1].name}: ${fmt(pair[1].views)}</p></div><button id="next">${state.round===rounds.length-1?'Play again':'Next round'} →</button></div>`:''}<p class="note">Real YouTube clips. View counts are illustrative demo values, not live data. Virtual coins only.</p><div class="steps"><div><b>01</b><span><strong>Get a feel.</strong><small>Preview two corners of the internet.</small></span></div><div><b>02</b><span><strong>Make your call.</strong><small>Back the one you think went bigger.</small></span></div><div><b>03</b><span><strong>Meet the numbers.</strong><small>Sometimes, a cat beats everything.</small></span></div></div></section></main><footer><span>Trust your taste. Question the algorithm.</span><a href="./market.html">Try the live prediction market ↗</a><span>A historical prediction game. Made for the plot.</span></footer><dialog id="how"><button id="close" class="close">×</button><h2>How to play</h2><p>Watch two clips, pick the one with more views, and stake virtual coins. A correct pick pays back twice your stake. Your progress stays in this browser.</p><p>View counts here are illustrative. For real devnet trading, use the prediction market link below the game.</p></dialog>`;
document.querySelectorAll<HTMLButtonElement>('[data-stake]').forEach(b=>b.onclick=()=>{state.stake=Number(b.dataset.stake);save();render()});document.querySelectorAll<HTMLButtonElement>('[data-pick]').forEach(b=>b.onclick=()=>{if(state.result||state.coins<state.stake)return;const win=Number(b.dataset.pick)===(pair[0].views>pair[1].views?0:1);state.coins+=win?state.stake:-state.stake;state.streak=win?state.streak+1:0;state.best=Math.max(state.best,state.streak);state.result={win};save();render()});document.querySelectorAll<HTMLButtonElement>('[data-play]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.play);const box=$('#video'+i);box.style.backgroundImage='none';box.innerHTML=`<iframe title="${pair[i].name}" src="https://www.youtube-nocookie.com/embed/${pair[i].id}?autoplay=1" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`});const next=document.querySelector<HTMLButtonElement>('#next');if(next)next.onclick=()=>{state.round=state.round===rounds.length-1?0:state.round+1;state.result=null;save();render()};const modal=$('#how') as HTMLDialogElement;($('#info') as HTMLButtonElement).onclick=()=>modal.showModal();($('#close') as HTMLButtonElement).onclick=()=>modal.close()}
render();
